---

- name: Install required for basic tasks packages for all instances
  hosts: all
  become: true

  tasks:
  - name: installing apache and php package for Ubuntu
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"
  
  - name: installing apache and php package for CentOS
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"
