---

- name: Install required for basic tasks packages for all instances
  hosts: all
  become: true

  tasks:
  - name: installing apache and php package
    package:
      name: 
        - " {{ apache_package }} "
        - " {{ php_package }} "
      state: latest
      update_cache: yes
    

