---

- name: Install required updates for [@@@ all servers @@@]
  hosts: all
  become: true

  pre_tasks:
  - name: install updates (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install updates (CentOS and Red Hat)
    tags: always
    yum:
      update_only: yes
      update_cache: yes
    when: ansible_distribution in ["CentOS", "Red Hat"]


- name: Install required packages for [@@@ Web servers @@@]
  hosts: web_servers
  become: true

  tasks:
  - name: Install apache and php for Ubuntu servers
    tags: apache,php,ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: Install apache and php for CentOS and Red Hat servers
    tags: apache,php,centos,redhat 
    yum:
      name:
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution in ["CentOS", "Red Hat"]


- name: Install required packages for [@@@ DB servers @@@]
  hosts: db_servers
  become: true

  tasks:
  - name: Install mariaDB for Ubuntu servers
    tags: mariadb,ubuntu
    apt:
      name:
        - mariadb-server
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: Install apache and php for CentOS and Red Hat servers
    tags: mariadb,centos,redhat
    yum:
      name:
        - mariadb
      state: latest
      update_cache: yes
    when: ansible_distribution in ["CentOS", "Red Hat"]
