---

- name: Install required updates for [@@@ all servers @@@]
  hosts: all
  become: true

  pre_tasks:
  - name: install updates (Ubuntu)
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"

  - name: install updates (CentOS and Red Hat)
    tags: always
    yum:
      update_cache: yes
    changed_when: false
    when: ansible_distribution in ["CentOS", "Red Hat"]


- hosts: all
  become: true
  roles:
    - base

- hosts: workstation
  become: true
  roles:
    - workstation

- hosts: web_servers
  become: true
  roles:
    - web_servers

- hosts: db_servers
  become: true
  roles:
    - db_servers
