- name: install mariadb server package (CentOS and Red Hat)
  tags: centos,db,mariadb
  yum:
    name: mariadb
    state: latest
  when: ansible_distribution in ["CentOS", "Red Hat"]
 
- name: install mariadb server
  tags: db,mariadb,ubuntu
  apt:
    name: mariadb-server
    state: latest
  when: ansible_distribution == "Ubuntu"
